"""
WTSA — Fingerprinter
Phase 1: Detects backend language, database type, WAF, and input reflection points.
Produces a TargetContext object that drives all downstream decisions.
"""

import re
import time
import asyncio
import httpx
from urllib.parse import urlparse, urlencode, urljoin
from typing import Optional
from .models import TargetContext


# ── Signature databases ──────────────────────────────────────────────────────

BACKEND_SIGNATURES = {
    "PHP": [
        r"X-Powered-By: PHP",
        r"\.php(\?|$|#)",
        r"PHPSESSID",
        r"Strict-Transport-Security.*php",
        r"Fatal error.*on line \d+",
        r"Warning:.*in /.*\.php",
        r"<?php",
    ],
    "Python": [
        r"X-Powered-By: Express",
        r"Django",
        r"Flask",
        r"Werkzeug",
        r"wsgi",
        r"\.py(\?|$|#)",
        r"gunicorn",
    ],
    "Node.js": [
        r"X-Powered-By: Express",
        r"connect\.sid",
        r"\.js(\?|$|#)",
        r"node\.js",
        r"express",
    ],
    "Java": [
        r"X-Powered-By:.*JSP",
        r"JSESSIONID",
        r"\.jsp(\?|$|#)",
        r"javax\.",
        r"java\.lang\.",
        r"Apache Tomcat",
        r"JBoss",
    ],
    "Ruby": [
        r"X-Powered-By:.*Phusion Passenger",
        r"_session_id",
        r"\.rb(\?|$|#)",
        r"Ruby on Rails",
        r"ActionController",
    ],
}

DB_SIGNATURES = {
    "MySQL": [
        r"You have an error in your SQL syntax",
        r"mysql_fetch_array\(\)",
        r"MySQL server version",
        r"supplied argument is not a valid MySQL",
        r"MySQLSyntaxErrorException",
        r"com\.mysql\.jdbc",
        r"Zend_Db_Adapter_Mysqli",
    ],
    "PostgreSQL": [
        r"PostgreSQL.*ERROR",
        r"Warning.*pg_",
        r"valid PostgreSQL result",
        r"Npgsql\.",
        r"PG::SyntaxError",
        r"org\.postgresql",
        r"ERROR:\s+syntax error at or near",
    ],
    "MSSQL": [
        r"Unclosed quotation mark after the character string",
        r"Microsoft OLE DB Provider for SQL Server",
        r"ODBC SQL Server Driver",
        r"SQLServer JDBC Driver",
        r"com\.microsoft\.sqlserver",
        r"Incorrect syntax near",
        r"mssql_query\(\)",
    ],
    "SQLite": [
        r"SQLite/JDBCDriver",
        r"SQLite\.Exception",
        r"System\.Data\.SQLite\.SQLiteException",
        r"sqlite3\.OperationalError",
        r"unrecognized token:",
        r"no such column:",
    ],
    "MongoDB": [
        r"MongoError",
        r"MongoNetworkError",
        r"Mongo::Error",
        r"pymongo\.errors",
        r"com\.mongodb",
    ],
}

WAF_SIGNATURES = {
    "Cloudflare": [
        r"cloudflare",
        r"cf-ray",
        r"__cfduid",
        r"Attention Required! \| Cloudflare",
        r"cf_clearance",
    ],
    "ModSecurity": [
        r"Mod_Security",
        r"ModSecurity",
        r"NOYB",
        r"This error was generated by Mod_Security",
    ],
    "Akamai": [
        r"AkamaiGHost",
        r"akamai",
        r"Reference #\d+\.\d+",
    ],
    "AWS WAF": [
        r"AWS Web Application Firewall",
        r"Request blocked",
        r"x-amzn-requestid",
    ],
}

# Probe string that triggers most WAFs
WAF_PROBE = "<script>alert(1)</script>'/\"/*--"


class Fingerprinter:
    def __init__(self, session: Optional[httpx.AsyncClient] = None,
                 cookies: dict = None,
                 headers: dict = None,
                 rate_limit: int = 10):
        self.cookies    = cookies or {}
        self.headers    = headers or {}
        self.rate_limit = rate_limit
        self._last_req  = 0.0

    async def _get(self, url: str, params: dict = None,
                   timeout: float = 10.0) -> httpx.Response:
        # Rate limiting
        gap = 1.0 / self.rate_limit
        elapsed = time.monotonic() - self._last_req
        if elapsed < gap:
            await asyncio.sleep(gap - elapsed)
        self._last_req = time.monotonic()

        async with httpx.AsyncClient(
            cookies=self.cookies,
            headers=self.headers,
            follow_redirects=True,
            timeout=timeout,
            verify=False,
        ) as client:
            return await client.get(url, params=params)

    # ── Public entry point ───────────────────────────

    async def fingerprint(self, url: str) -> TargetContext:
        ctx = TargetContext(url=url)

        try:
            resp = await self._get(url)
        except Exception as e:
            ctx.error_signatures.append(f"Connection error: {e}")
            return ctx

        ctx.response_headers = dict(resp.headers)
        combined = _headers_str(resp) + resp.text

        ctx.backend_language = _match_first(combined, BACKEND_SIGNATURES, "Unknown")
        ctx.database_type    = _match_first(combined, DB_SIGNATURES, "Unknown")
        ctx.waf_detected     = await self._detect_waf(url, combined)

        # Error signature collection
        for db, patterns in DB_SIGNATURES.items():
            for pattern in patterns:
                if re.search(pattern, combined, re.IGNORECASE):
                    ctx.error_signatures.append(f"[{db}] {pattern}")

        # SPA detection: look for JS framework markers
        ctx.spa_detected = bool(re.search(
            r'(ng-app|__next|__nuxt|<div id=["\']app["\']|react|vue\.js)',
            resp.text, re.IGNORECASE
        ))

        # Auth detection
        ctx.auth_required = bool(re.search(
            r'(login|signin|auth|password|username)',
            resp.text, re.IGNORECASE
        )) or resp.status_code in (401, 403)

        ctx.fingerprint_confidence = _confidence_score(ctx)
        return ctx

    async def _detect_waf(self, url: str, initial_body: str) -> str:
        # First check initial response
        for waf, patterns in WAF_SIGNATURES.items():
            for p in patterns:
                if re.search(p, initial_body, re.IGNORECASE):
                    return waf

        # Probe with a known WAF trigger
        parsed = urlparse(url)
        probe_url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"
        try:
            resp = await self._get(probe_url, params={"q": WAF_PROBE})
            probe_body = _headers_str(resp) + resp.text
            for waf, patterns in WAF_SIGNATURES.items():
                for p in patterns:
                    if re.search(p, probe_body, re.IGNORECASE):
                        return waf
            if resp.status_code in (403, 406, 429, 503):
                return "Unknown WAF"
        except Exception:
            pass

        return "None"

    async def map_reflection_points(self, url: str, inputs: list) -> list[str]:
        """
        Send canary tokens into each input and track where they reflect.
        Returns list of reflection context strings.
        """
        reflection_points = []
        for inp in inputs:
            canary = f"WTSA_CANARY_{inp.param_name[:6].upper()}"
            try:
                if inp.method.upper() == "GET":
                    resp = await self._get(inp.url, params={inp.param_name: canary})
                else:
                    async with httpx.AsyncClient(
                        cookies=self.cookies, headers=self.headers,
                        follow_redirects=True, timeout=10.0, verify=False
                    ) as client:
                        resp = await client.post(
                            inp.form_action or inp.url,
                            data={inp.param_name: canary}
                        )

                if canary in resp.text:
                    # Find context around the reflection
                    idx = resp.text.find(canary)
                    ctx_snippet = resp.text[max(0, idx-60):idx+60]
                    reflection_points.append(
                        f"{inp.url}?{inp.param_name}={canary} → reflects in: ...{ctx_snippet}..."
                    )
                    inp.reflects = True
                    inp.context  = ctx_snippet
            except Exception:
                pass

        return reflection_points


# ── Helpers ──────────────────────────────────────────────────────────────────

def _headers_str(resp: httpx.Response) -> str:
    return "\n".join(f"{k}: {v}" for k, v in resp.headers.items())


def _match_first(text: str, signatures: dict, default: str) -> str:
    for name, patterns in signatures.items():
        for pattern in patterns:
            if re.search(pattern, text, re.IGNORECASE):
                return name
    return default


def _confidence_score(ctx: TargetContext) -> str:
    score = 0
    if ctx.backend_language != "Unknown": score += 2
    if ctx.database_type    != "Unknown": score += 2
    if ctx.error_signatures:              score += 1
    if ctx.waf_detected     != "None":    score += 1
    if score >= 4:  return "High"
    if score >= 2:  return "Medium"
    return "Low"
